# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zVU_w5qHnc9bqN5uLGm91bKqCSUflJyg

**GrayScaling**
"""

from PIL import Image
import matplotlib.pyplot as plt

img= Image.open("78.jpg")
img.show()
width,height=img.size
pix=img.load()
for i in range(width):
  for j in range(height):
    r,g,b=pix[i,j]
    gray = (r+g+b)/3
    pix[i,j]=(int(gray),int(gray),int(gray))
img.save("greyscale_a.jpg")
img1=Image.open("greyscale_a.jpg")

plt.imshow(img1)
plt.axis('off')
plt.show()

"""Thresholding"""

from PIL import Image
img= Image.open("greyscale_a.jpg")
img.show()
width,height=img.size
pix=img.load()
thresh=130;
for i in range(width):
  for j in range(height):
    r,g,b=pix[i,j]
    avg = (r+g+b)/3

    if avg>thresh:
      pix[i,j]=(255,255,255)
    else:
      pix[i,j]=(0,0,0)
    
img.save("outputThresh.jpg")
img1=Image.open("outputThresh.jpg")

plt.imshow(img1)
plt.axis('off')
plt.show()

"""Resizing"""

from PIL import Image
img=Image.open("outputThresh.jpg")
img.show()
width,height=img.size
pix=img.load()


newsize=(28,28)
img1=img.resize(newsize)

img1.save("outputnew.jpg")
img2=Image.open("outputnew.jpg")

plt.imshow(img2)
plt.axis('off')
plt.show()